port: /dev/ttyUSB0
rate: 15
joints: {
  arm_shoulder_pan_joint: {id: 1, neutral: 205, max_angle: 240, min_angle: -60, max_speed: 100},
  arm_shoulder_lift_joint: {id: 2, max_angle: 150, min_angle: -150, max_speed: 100},
  arm_wrist_flex_joint: {id: 3, max_angle: 150, min_angle: -150, max_speed: 100},
  gripper_joint: {id: 4, max_speed: 90, type: dynamixel},
}
controllers: {
  arm_controller: {
    type: follow_controller,
    joints: [arm_shoulder_pan_joint, arm_shoulder_lift_joint, arm_wrist_flex_joint],
    action_name: arm_controller/follow_joint_trajectory,
    onboard: false
  }
}
